apiVersion: 1

datasources:
  - name: Clickstream Postgres
    uid: clickstream-pg
    type: postgres
    access: proxy
    url: postgres:5432
    user: stream
    secureJsonData:
      password: stream
    jsonData:
      database: clickstream
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: false
